### ISSUE TITLE
Shutdown locks forever, JVM does not terminate

### ISSUE THREAD

**Issue by BastianVoigt** [findify/s3mock#135]
Using version 0.2.5

Calling first stop(), then shutdown()

"Thread-20" #60 prio=5 os_prio=0 tid=0x00007f5a88a72000 nid=0x7697 waiting on condition [0x00007f5a6dcee000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000072b90d2e8> (a scala.concurrent.impl.Promise$CompletionLatch)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:238)
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:254)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
        at scala.concurrent.Await$$$Lambda$615/2141872108.apply(Unknown Source)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:142)
        at io.findify.s3mock.S3Mock.shutdown(S3Mock.scala:87)
        at de.ottonow.billing.configuration.S3MockConfiguration.shutdown(S3MockConfiguration.kt:43)

**Comment by vladimirfx** [comment]
I was hit by this too. Is there any way to force shutdown?

**Comment by zonk911** [comment]
we encountered the same issue, we didn't shutdown or stopped explicitly we let the jvm shut it down on its own. this was our solution... the stop or shutdown never returned in our case

**Comment by tdurtschi** [comment]
We just hit this issue as well nearly 4 years after it was first reported. Is this repo actively maintained?

**Comment by vladimirfx** [comment]
No, obviously. We migrated to [s3proxy](https://github.com/gaul/s3proxy)
