### ISSUE TITLE
Errors with AWS S3 v2.1.0

### ISSUE THREAD

**Issue by daveg-hf** [findify/s3mock#138]
We had success using s3mock through use of 2.0.0-preview11.

Upon upgrade to the released 2.1.0, S3 throws SdkException "Data read has a different checksum than expected. Was -1864013060, but expected 774912850"

**Comment by er1c** [comment]
I'm getting an error about "no required 'Host'" header supplied, did you see this?

```
11:17:34.767 [pool-1-thread-1-ScalaTest-running-TestWebCat30AdminWSServerCatalogFilesAPI] INFO  t.w.w.v.TestWebCat30AdminWSServerCatalogFilesAPI - Starting embedded s3 server...done!
[WARN] [03/18/2019 11:17:35.494] [s3mock-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(s3mock)] Illegal request, responding with status '400 Bad Request': Request is missing required `Host` header
[info] - putCatalogFile && getCatalogFile && deleteGetFile *** FAILED ***
[info]   java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: null)
[info]   at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:61)
[info]   at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
[info]   at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
[info]   at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
[info]   at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[info]   at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
[info]   at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:75)
[info]   at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
[info]   at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
[info]   at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[info]   ...
[info]   Cause: software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: null)
[info]   at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:95)
[info]   at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:55)
[info]   at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:127)
[info]   at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:86)
[info]   at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88)
[info]   at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
[info]   at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[info]   at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
[info]   at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129)
[info]   at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:180)
```

Did you also encounter this error too?
