### ISSUE TITLE
A way to clean bucket between tests?

### ISSUE THREAD

**Issue by mpaluchowski** [findify/s3mock#17]
I'm trying to make my tests with S3Mock independent and to achieve that, clean, delete and recreate the bucket between tests. This is failing because of exceptions related to being unable to delete either a file or the bucket directory itself.

Here's my setup, roughly:

```java

@Before
public void setUp() throws Exception {
    s3Api = S3Mock.create(8001, System.getProperty("java.io.tmpdir") + "s3");
    s3Api.start();

    s3Client = new AmazonS3Client(new AnonymousAWSCredentials());
    s3Client.setEndpoint("http://127.0.0.1:8001");
    s3Client.createBucket(BUCKET_NAME);
}

@After
public void tearDown() throws Exception {
    for (S3ObjectSummary summary : s3Client.listObjects(BUCKET_NAME).getObjectSummaries()) {
        if (!summary.getKey().startsWith(".")) {
            s3Client.deleteObject(BUCKET_NAME, summary.getKey());
        }
    }
    s3Client.deleteBucket(BUCKET_NAME);
}
```

The `if (!summary.getKey().startsWith("."))` is there because of #16. Without it I'm getting:

```
10:35:58.759 [sqsmock-akka.actor.default-dispatcher-10] DEBUG io.findify.s3mock.provider.FileProvider - deleting bucket s://attachments
10:35:58.763 [sqsmock-akka.actor.default-dispatcher-10] ERROR io.findify.s3mock.route.DeleteBucket - DELETE bucket attachments failed: C:\Users\palucm01\AppData\Local\Temp\s3\attachments\.testKey
java.nio.file.AccessDeniedException: C:\Users\palucm01\AppData\Local\Temp\s3\attachments\.testKey
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at better.files.File.delete(File.scala:602)
        ...
```

while _with_ the `if` I'm getting:

```
10:37:09.110 [sqsmock-akka.actor.default-dispatcher-5] DEBUG io.findify.s3mock.provider.FileProvider - deleting bucket s://attachments
10:37:09.116 [sqsmock-akka.actor.default-dispatcher-5] ERROR io.findify.s3mock.route.DeleteBucket - DELETE bucket attachments failed: C:\Users\palucm01\AppData\Local\Temp\s3\attachments
java.nio.file.DirectoryNotEmptyException: C:\Users\palucm01\AppData\Local\Temp\s3\attachments
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at better.files.File.delete(File.scala:602)
	at io.findify.s3mock.provider.FileProvider.deleteBucket(FileProvider.scala:130)
        ...
```

and either way, I can't delete the directory.

**Comment by jimirocks** [comment]
@mpaluchowski I am using Junit's `TemporaryFolder` rule which ensures clean S3Mock backend directory quite fine

**Comment by shuttie** [comment]
I've updated the docs, so now you can use in-memory provider for that case.

**Comment by AlJohri** [comment]
@shuttie is there a way to clean up the entire memory contents after each test?

```java
public class SampleJavaClassTest {

    static S3Mock api = new S3Mock.Builder().withPort(8001).withInMemoryBackend().build();
    S3AsyncClient client = S3AsyncClient.builder()
        .serviceConfiguration(x -> x.pathStyleAccessEnabled(true))
        .endpointOverride(URI.create("http://localhost:8001"))
        .region(Region.US_WEST_2)
        .credentialsProvider(AnonymousCredentialsProvider.create())
        .build();

    @BeforeAll
    public static void setUp() throws URISyntaxException {
        api.start();
    }

    @AfterAll
    public static void teardown() {
        api.shutdown();
    }

    @Test
    public void testS3Mock_PutGet() throws InterruptedException, ExecutionException {
        String bucketName = "test-bucket";
        String input = "hello world";
        client.createBucket(r -> r.bucket(bucketName)).get();
        client.putObject(r -> r.bucket(bucketName).key("mykey"), AsyncRequestBody.fromString(input)).get();
        var responseBytes = client.getObject(r -> r.bucket(bucketName).key("mykey"), AsyncResponseTransformer.toBytes()).get();
        assertEquals(responseBytes.asUtf8String(), input);
        
        // clean up
        client.deleteBucket(r -> r.bucket(bucketName)).get();
    }
]
```

I want to do some sort of `@BeforeEach` which cleans up everything before each test instead of manually deleting the bucket as done above.
