### ISSUE TITLE
using s3mock from awscli 

### ISSUE THREAD

**Issue by psihodelik** [findify/s3mock#3]
after running s3mock and then with aws cli trying to create bucket getting error:

A client error (405) occurred when calling the CreateBucket operation: Method Not Allowed

cmd:
AWS_ACCESS_KEY_ID=4324324234 AWS_SECRET_ACCESS_KEY=3412342 aws s3api create-bucket --bucket demo --endpoint-url http://0.0.0.0:80/    

When creating bucket with java aws sdk it works.

Is there something I am missing?

**Comment by psihodelik** [comment]
if it helps this is aws cli debug trace:

2016-08-19 20:02:36,966 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.1 Python/3.5.2 Linux/4.4.0-34-generic botocore/1.3.23
2016-08-19 20:02:36,967 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'create-bucket', '--bucket', 'demo', '--endpoint-url', 'http://127.0.0.1:8001/', '--debug']
2016-08-19 20:02:36,967 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fe3488fbd90>
2016-08-19 20:02:36,967 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fe348955b70>
2016-08-19 20:02:36,967 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-08-19 20:02:36,971 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7fe348e8e268>
2016-08-19 20:02:36,971 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2016-08-19 20:02:36,972 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x7fe3489600d0>
2016-08-19 20:02:36,973 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('acl', <awscli.arguments.CLIArgument object at 0x7fe348783278>), ('bucket', <awscli.arguments.CLIArgument object at 0x7fe3487832e8>), ('create-bucket-configuration', <awscli.arguments.CLIArgument object at 0x7fe348783320>), ('grant-full-control', <awscli.arguments.CLIArgument object at 0x7fe348783358>), ('grant-read', <awscli.arguments.CLIArgument object at 0x7fe3487833c8>), ('grant-read-acp', <awscli.arguments.CLIArgument object at 0x7fe348783390>), ('grant-write', <awscli.arguments.CLIArgument object at 0x7fe348783400>), ('grant-write-acp', <awscli.arguments.CLIArgument object at 0x7fe348783438>)])
2016-08-19 20:02:36,973 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_streaming_output_arg at 0x7fe348a6fbf8>
2016-08-19 20:02:36,973 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_cli_input_json at 0x7fe348955510>
2016-08-19 20:02:36,974 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function unify_paging_params at 0x7fe348a84f28>
2016-08-19 20:02:36,974 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_generate_skeleton at 0x7fe3489558c8>
2016-08-19 20:02:36,974 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.create-bucket: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fe3487834a8>>
2016-08-19 20:02:36,974 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.create-bucket: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fe3487834e0>>
2016-08-19 20:02:36,975 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.acl: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,975 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.bucket: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,975 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.create-bucket: calling handler <awscli.argprocess.ParamShorthand object at 0x7fe348a69518>
2016-08-19 20:02:36,975 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'demo' for parameter "bucket": 'demo'
2016-08-19 20:02:36,975 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.create-bucket-configuration: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-full-control: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-read: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-read-acp: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-write: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-write-acp: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.cli-input-json: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.generate-cli-skeleton: calling handler <function uri_param at 0x7fe348ada9d8>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.create-bucket: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fe3487834e0>>
2016-08-19 20:02:36,976 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.create-bucket: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fe3487834a8>>
2016-08-19 20:02:36,976 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-08-19 20:02:36,976 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2016-08-19 20:02:36,977 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-08-19 20:02:36,978 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fe348e73268>
2016-08-19 20:02:36,978 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fe348ed5840>
2016-08-19 20:02:36,982 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-08-19 20:02:36,982 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x7fe348e8df28>
2016-08-19 20:02:36,983 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.CreateBucket: calling handler <function add_expect_header at 0x7fe348e8e488>
2016-08-19 20:02:36,983 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7fe348790c18> (verify_ssl=True) with params: {'headers': {'User-Agent': 'aws-cli/1.10.1 Python/3.5.2 Linux/4.4.0-34-generic botocore/1.3.23'}, 'url_path': '/demo', 'query_string': {}, 'url': 'http://127.0.0.1:8001/demo', 'method': 'PUT', 'body': b''}
2016-08-19 20:02:36,983 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.CreateBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fe348721320>>
2016-08-19 20:02:36,983 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2016-08-19 20:02:36,983 - MainThread - botocore.auth - DEBUG - HTTP request method: PUT
2016-08-19 20:02:36,983 - MainThread - botocore.auth - DEBUG - StringToSign:
PUT


Fri, 19 Aug 2016 17:02:36 GMT
/demo
2016-08-19 20:02:36,985 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2016-08-19 20:02:36,987 - MainThread - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by psihodelik** [comment]
I am sorry, above is debug trace when  s3mock is run insdie docker cotnainer...
this is trace when trying to create bucket with s3mock server and awscli being next to each other:

 AWS_SECRET_ACCESS_KEY=3412342 aws s3api create-bucket --bucket demo --endpoint-url http://127.0.0.1:80/ --debug
2016-08-19 17:14:09,060 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.10.1 Python/3.5.2 Linux/4.4.0-34-generic botocore/1.3.23
2016-08-19 17:14:09,061 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3api', 'create-bucket', '--bucket', 'demo', '--endpoint-url', 'http://127.0.0.1:80/', '--debug']
2016-08-19 17:14:09,061 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fbc78019d90>
2016-08-19 17:14:09,061 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fbc78070b70>
2016-08-19 17:14:09,061 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-08-19 17:14:09,065 - MainThread - botocore.hooks - DEBUG - Event service-data-loaded.s3: calling handler <function register_retries_for_service at 0x7fbc785a9268>
2016-08-19 17:14:09,066 - MainThread - botocore.handlers - DEBUG - Registering retry handlers for service: s3
2016-08-19 17:14:09,067 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3api: calling handler <function add_waiters at 0x7fbc7807d0d0>
2016-08-19 17:14:09,068 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('acl', <awscli.arguments.CLIArgument object at 0x7fbc77ea00b8>), ('bucket', <awscli.arguments.CLIArgument object at 0x7fbc77ea0128>), ('create-bucket-configuration', <awscli.arguments.CLIArgument object at 0x7fbc77ea0160>), ('grant-full-control', <awscli.arguments.CLIArgument object at 0x7fbc77ea0198>), ('grant-read', <awscli.arguments.CLIArgument object at 0x7fbc77ea0208>), ('grant-read-acp', <awscli.arguments.CLIArgument object at 0x7fbc77ea01d0>), ('grant-write', <awscli.arguments.CLIArgument object at 0x7fbc77ea0240>), ('grant-write-acp', <awscli.arguments.CLIArgument object at 0x7fbc77ea0278>)])
2016-08-19 17:14:09,068 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_streaming_output_arg at 0x7fbc7818bbf8>
2016-08-19 17:14:09,068 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_cli_input_json at 0x7fbc78070510>
2016-08-19 17:14:09,068 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function unify_paging_params at 0x7fbc781a0f28>
2016-08-19 17:14:09,069 - MainThread - botocore.hooks - DEBUG - Event building-argument-table.s3api.create-bucket: calling handler <function add_generate_skeleton at 0x7fbc780708c8>
2016-08-19 17:14:09,069 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.create-bucket: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fbc77ea02e8>>
2016-08-19 17:14:09,069 - MainThread - botocore.hooks - DEBUG - Event before-building-argument-table-parser.s3api.create-bucket: calling handler <bound method OverrideRequiredArgsArgument.override_required_args of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fbc77ea0320>>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.acl: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.bucket: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.s3.create-bucket: calling handler <awscli.argprocess.ParamShorthand object at 0x7fbc78193358>
2016-08-19 17:14:09,070 - MainThread - awscli.arguments - DEBUG - Unpacked value of 'demo' for parameter "bucket": 'demo'
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.create-bucket-configuration: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-full-control: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-read: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-read-acp: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-write: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.grant-write-acp: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.cli-input-json: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.s3.create-bucket.generate-cli-skeleton: calling handler <function uri_param at 0x7fbc781f59d8>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.create-bucket: calling handler <bound method GenerateCliSkeletonArgument.generate_json_skeleton of <awscli.customizations.generatecliskeleton.GenerateCliSkeletonArgument object at 0x7fbc77ea0320>>
2016-08-19 17:14:09,070 - MainThread - botocore.hooks - DEBUG - Event calling-command.s3api.create-bucket: calling handler <bound method CliInputJSONArgument.add_to_call_parameters of <awscli.customizations.cliinputjson.CliInputJSONArgument object at 0x7fbc77ea02e8>>
2016-08-19 17:14:09,071 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-08-19 17:14:09,071 - MainThread - botocore.credentials - INFO - Found credentials in environment variables.
2016-08-19 17:14:09,071 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-08-19 17:14:09,072 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fbc7860b268>
2016-08-19 17:14:09,073 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fbc785ec840>
2016-08-19 17:14:09,075 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-08-19 17:14:09,076 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.CreateBucket: calling handler <function validate_bucket_name at 0x7fbc785a7f28>
2016-08-19 17:14:09,076 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.CreateBucket: calling handler <function add_expect_header at 0x7fbc785a9488>
2016-08-19 17:14:09,076 - MainThread - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7fbc77eabc88> (verify_ssl=True) with params: {'body': b'', 'url': 'http://127.0.0.1:80/demo', 'method': 'PUT', 'headers': {'User-Agent': 'aws-cli/1.10.1 Python/3.5.2 Linux/4.4.0-34-generic botocore/1.3.23'}, 'url_path': '/demo', 'query_string': {}}
2016-08-19 17:14:09,076 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.CreateBucket: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fbc77ebd160>>
2016-08-19 17:14:09,076 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.
2016-08-19 17:14:09,076 - MainThread - botocore.auth - DEBUG - HTTP request method: PUT
2016-08-19 17:14:09,077 - MainThread - botocore.auth - DEBUG - StringToSign:
PUT


Fri, 19 Aug 2016 17:14:09 GMT
/demo
2016-08-19 17:14:09,078 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2016-08-19 17:14:09,377 - MainThread - botocore.parsers - DEBUG - Response headers: {'Server': 'akka-http/2.4.9-RC2', 'Allow': 'GET', 'Content-Length': '47', 'Date': 'Fri, 19 Aug 2016 17:14:09 GMT', 'Content-Type': 'text/plain; charset=UTF-8'}
2016-08-19 17:14:09,377 - MainThread - botocore.parsers - DEBUG - Response body:
b'HTTP method not allowed, supported methods: GET'
2016-08-19 17:14:09,378 - MainThread - botocore.parsers - DEBUG - Exception caught when parsing error response body:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/parsers.py", line 350, in _parse_xml_string_to_dom
    parser.feed(xml_string)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/botocore/parsers.py", line 695, in _do_error_parse
    return self._parse_error_from_body(response)
  File "/usr/lib/python3/dist-packages/botocore/parsers.py", line 717, in _parse_error_from_body
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/usr/lib/python3/dist-packages/botocore/parsers.py", line 355, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
botocore.parsers.ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received:
b'HTTP method not allowed, supported methods: GET'
2016-08-19 17:14:09,378 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CreateBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7fbc77e88c88>
2016-08-19 17:14:09,379 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2016-08-19 17:14:09,379 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.CreateBucket: calling handler <function enhance_error_msg at 0x7fbc78070158>
2016-08-19 17:14:09,379 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.CreateBucket: calling handler <awscli.errorhandler.ErrorHandler object at 0x7fbc78193438>
2016-08-19 17:14:09,379 - MainThread - awscli.errorhandler - DEBUG - HTTP Response Code: 405
2016-08-19 17:14:09,379 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/share/awscli/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/share/awscli/awscli/clidriver.py", line 377, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/share/awscli/awscli/clidriver.py", line 546, in __call__
    call_parameters, parsed_globals)
  File "/usr/share/awscli/awscli/clidriver.py", line 670, in invoke
    **parameters)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 403, in _make_api_call
    model=operation_model, context=request_context
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/usr/share/awscli/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
awscli.errorhandler.ClientError: A client error (405) occurred when calling the CreateBucket operation: Method Not Allowed
2016-08-19 17:14:09,380 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255

A client error (405) occurred when calling the CreateBucket operation: Method Not Allowed

**Comment by shuttie** [comment]
Thanks for the report, the bug is fixed in 0.1.2. See test: https://github.com/findify/s3mock/blob/master/src/test/scala/io/findify/s3mock/awscli/PutBucketTest.scala
