### ISSUE TITLE
Payload > 8MB not supported

### ISSUE THREAD

**Issue by RovoMe** [findify/s3mock#31]
We have a special treatment for larger files in our application which should externalize files exceeding a certain threshold to S3 rather than to our database. In order to test the upload part to S3 we currently test s3mock, however we get an exception thrown by Akka that the actual entity size exceeded the content length limit:

```
[ERROR] [02/22/2017 14:16:52.829] [sqsmock-akka.actor.default-dispatcher-6] [akka://sqsmock/user/StreamSupervisor-0/flow-4-0-unknown-operation] Error during preStart in [akka.http.scaladsl.model.HttpEntity$Limitable@6b9826b2]
EntityStreamSizeException: actual entity size (Some(10039231)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
	at akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1.preStart(HttpEntity.scala:607)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:520)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:380)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:538)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:586)
	at akka.actor.Actor.aroundPreStart(Actor.scala:504)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:504)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I've tried to set the `akka.http.server.parsing.max-content-length` (client as well) as System.property though without any success. Is there a possibility to specify this threshold via the S3Mock interface somehow? I haven't found anything in either the `Http.ServerBinding` object returned from `s3Mock.start()` nor from the `Provider` returned via `s3Mock.p()`.

PS: you should also update the README.md and update the Maven version to 0.1.6 as 0.1.5 is not available and your Scala version also refers to 0.1.6 also.

**Comment by shuttie** [comment]
Fixed in https://github.com/findify/s3mock/commit/e4e577b26ec2e012b274e06e93de85d1270dbde3
