### ISSUE TITLE
Cannot find aka.stream.Graph.module method

### ISSUE THREAD

**Issue by leerobert** [findify/s3mock#63]
Using 0.2.3 on scala 2.11.11 play application, I'm getting this error out of the box

```
java.lang.NoSuchMethodError: akka.stream.Graph.module()Lakka/stream/impl/StreamLayout$Module;

	at akka.stream.Fusing$FusedGraph$.unapply(Fusing.scala:56)
	at akka.stream.impl.fusing.Fusing$.aggressive(Fusing.scala:35)
	at akka.stream.Fusing$.aggressive(Fusing.scala:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at akka.http.impl.util.StreamUtils$$anon$13.aggressive(StreamUtils.scala:259)
	at akka.http.impl.util.StreamUtils$.fuseAggressive(StreamUtils.scala:272)
	at akka.http.scaladsl.HttpExt.fuseServerFlow(Http.scala:87)
	at akka.http.scaladsl.HttpExt.bindAndHandle(Http.scala:181)
	at io.findify.s3mock.S3Mock.start(S3Mock.scala:62)```

**Comment by carstenlenz** [comment]
What version of Play are you using?

**Comment by shuttie** [comment]
I guess it's play 2.5 which requires akka 2.4. And s3mock uses akka 2.5, which is not binary compatible.
