### ISSUE TITLE
Multi-part upload are not working

### ISSUE THREAD

**Issue by sheinbergon** [findify/s3mock#72]
When trying the multipart upload functionality, it tries to fetch the key immediately after initiating the upload ( probably as part of calling the `waitForCompletion()` method ). Happens both for InMemory of File Providers.

````
INFO  - multipart upload start to segment-uploader-test/stream/dummyStream/context/dummyContext/segments/segment.mp4
2017-10-26 15:19:47,911 [s3mock-akka.actor.default-dispatcher-4] INFO  - cannot delete object segment-uploader-test/stream/dummyStream/context/dummyContext/segments/segment.mp4: no such key
2017-10-26 15:19:47,918 [s3-transfer-manager-worker-1] INFO  - Unable to abort multipart upload, you may need to manually remove uploaded parts: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null)
com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4168) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.abortMultipartUpload(AmazonS3Client.java:2924) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.performAbortMultipartUpload(UploadCallable.java:219) [aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInParts(UploadCallable.java:195) [aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123) [aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143) [aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48) [aws-java-sdk-s3-1.11.149.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
2017-10-26 15:19:47,924 [pool-4-thread-1] ERROR - Error encountered during task execution - 
com.agt.segment.upload.exception.SegmentUploadException: Unable to upload segment '/tmp/test-storage/streams/dummyStream/contexts/dummyContext/segments/segment.mp4'
	at com.agt.segment.upload.impl.S3CamelUploadTaskOpsFacade.uploadSegment(S3CamelUploadTaskOpsFacade.java:67) ~[classes/:?]
	at com.agt.segment.upload.UploadTask.run(UploadTask.java:74) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The resource you requested does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.149.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4168) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.listParts(AmazonS3Client.java:3112) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.identifyExistingPartsForResume(UploadCallable.java:312) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadPartsInParallel(UploadCallable.java:287) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInParts(UploadCallable.java:188) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48) ~[aws-java-sdk-s3-1.11.149.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	... 3 more


````

**Comment by shuttie** [comment]
Can you provide the reproducible example? As there are tests for multipart uploads and all of them are surprisingly green both for in-memory and on-disk backends.

**Comment by git-josip** [comment]
I am experiencing same behaviour. If I use just amazonS3Client putObjectRequest then uploads works with s3Mock in memory. 
If I try to use TransferManager upload does not work, with error same as above. 

```2019-02-05 10:20:41.720  INFO 87610 --- [           main] io.findify.s3mock.S3Mock                 : bound to 0.0.0.0:8010
2019-02-05 10:20:42.230  INFO 87610 --- [lt-dispatcher-3] io.findify.s3mock.route.ListBucket       : listing bucket myo-test with prefix=None, delimiter=None
2019-02-05 10:20:42.380  INFO 87610 --- [lt-dispatcher-3] io.findify.s3mock.route.CreateBucket     : PUT bucket myo-test
2019-02-05 10:21:05.425  INFO 87610 --- [lt-dispatcher-3] i.f.s.route.PutObjectMultipartStart      : multipart upload start to myo-test/test_key_1549358442390
2019-02-05 10:21:05.495  WARN 87610 --- [lt-dispatcher-6] i.f.s3mock.provider.InMemoryProvider     : key does not exist
2019-02-05 10:21:05.495  INFO 87610 --- [lt-dispatcher-6] io.findify.s3mock.route.DeleteObject     : cannot delete object myo-test/test_key_1549358442390: no such key
2019-02-05 10:21:05.512  INFO 87610 --- [anager-worker-1] c.a.s.s.t.internal.UploadCallable        : Unable to abort multipart upload, you may need to manually remove uploaded parts: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null; S3 Extended Request ID: null)

com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: null; S3 Extended Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1701) ~[aws-java-sdk-core-1.11.490.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1356) ~[aws-java-sdk-core-1.11.490.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1102) ~[aws-java-sdk-core-1.11.490.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759) ~[aws-java-sdk-core-1.11.490.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733) ~[aws-java-sdk-core-1.11.490.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715) ~[aws-java-sdk-core-1.11.490.jar:na]
```

code example:

**Comment by rage-shadowman** [comment]
The bug is in the `abortMultiPartUpload` call. If you push an object to that path before starting your multi-part upload, then the abort removes the previously existing `S3Object`, but if no such object existed when you called the abort method, it fails, even if some parts were uploaded, with the following error (for bucket "bucket" and objectKey "objectkey.txt"):
> key does not exist
> cannot delete object bucket/objectkey.txt: no such key

To test this out, simply run the following:
```
// create new empty bucket
String bucketName = "bucket-name";
String objectKey = "objectKey.txt";
amazonS3.createBucket(bucketName);

// uncomment the following to upload a pre-existing object to see the abort method succeed and remove said pre-existing object
//amazonS3.putObject(bucketName, objectKey, "some contents");

// start a multi-part upload
InitiateMultipartUploadRequest multipartUploadRequest = new InitiateMultipartUploadRequest(bucketName, objectKey);
InitiateMultipartUploadResult uploadResult = amazonS3.initiateMultipartUpload(multipartUploadRequest);
String uploadId = uploadResult.getUploadId();

// you may upload parts here if you wish, that will not affect the outcome

// abort the multi-part upload
AbortMultipartUploadRequest request = new AbortMultipartUploadRequest(bucketName, objectKey, uploadId);
amazonS3.abortMultipartUpload(request);
```

**Comment by amarbardolia** [comment]
Getting same issue as @sheinbergon while trying to abort MPU
