### ISSUE TITLE
S3mock to support https 

### ISSUE THREAD

**Issue by rrajendran** [findify/s3mock#74]
Trying to test put operation with SSEAwsKeyManagementParams encryption enabled.
**PutObject**

` PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, key, inputStream,metadata);
 putObjectRequest.withSSEAwsKeyManagementParams(new SSEAwsKeyManagementParams());
`

**Exception**

`com.amazonaws.SdkClientException: Unable to execute HTTP request: Unrecognized SSL message, plaintext connection?

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2084)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObject(AmazonS3Client.java:2070)`

**Comment by shuttie** [comment]
Technically it's possible to use typesafe SSLConfig for HTTPS testing, but the setup is quite tricky both for server and client (generating CA, certs, importing them to keystores, etc.). PR with this feature is highly appreciated :)

**Comment by rrajendran** [comment]
Unfortunately, I don't have scala skills to raise a pull request.

**Comment by stevedefazio** [comment]
Has anybody run with this? I can see this thread is a year and a half old.

**Comment by deeptianand-babylon** [comment]
I am also curious about this issue.
