### ISSUE TITLE
Alpakka S3 multipart upload fails when using file provider with key containing percentage character

### ISSUE THREAD

**Issue by vizog** [findify/s3mock#77]
here is an example failing code:
add dependency to build.sbt:
`"com.lightbend.akka" %% "akka-stream-alpakka-s3" % "0.14"`

add configuration:
```
akka.stream.alpakka.s3 {
 
  buffer = "disk"
  disk-buffer-path = ""

  proxy {
    host = "localhost"
    port = 8002
    secure = false
  }
  aws {
    credentials {
      provider = static
      access-key-id = "anykey"
      secret-access-key = "secret"
    }
  }
  path-style-access = true
```

Main class:

```
package io.findify.s3mock;

import akka.Done;
import akka.actor.ActorSystem;
import akka.actor.dsl.Creators;
import akka.http.javadsl.model.ContentType;
import akka.http.javadsl.model.ContentTypes;
import akka.stream.ActorMaterializer;
import akka.stream.IOResult;
import akka.stream.Materializer;
import akka.stream.alpakka.s3.S3Settings;
import akka.stream.alpakka.s3.javadsl.S3Client;
import akka.stream.javadsl.Sink;
import akka.stream.javadsl.Source;
import akka.stream.javadsl.StreamConverters;
import akka.util.ByteString;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.AnonymousAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;

import java.io.FileInputStream;
import java.util.concurrent.CompletionStage;

public class AlpakkaExample {

    private  S3Mock api;
    ActorSystem system = ActorSystem.create("alpakka");
    ActorMaterializer materializer = ActorMaterializer.create(system);

    S3Client s3Client = createS3Client(system);
    private String s3BucketName = "test-bucket";

    public AlpakkaExample() {
        api = S3Mock.create(8002, "/tmp/s3");
//using the memroy provider works fine:
//     api = new S3Mock.Builder().withInMemoryBackend().withPort(8002).build();

        api.start();

        AmazonS3 client = AmazonS3ClientBuilder
            .standard()
            .withPathStyleAccessEnabled(true)
            .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:8002", "us-east-1"))
            .withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials()))
            .build();
        client.createBucket(s3BucketName);
    }

    private S3Client createS3Client(ActorSystem system) {
        return new S3Client(S3Settings.create(system), system, materializer);
    }

    Sink<ByteString, CompletionStage<Done>> upload(String key, ContentType actualContentType) {

        return s3Client.multipartUpload(s3BucketName, key, actualContentType)
            .mapMaterializedValue(c -> c.handle((result, error) -> {
                if (error != null) {
                    error.printStackTrace();
                    throw new RuntimeException(error);
                }
                return Done.getInstance();}
            ));
    }

    public void testUpload(String key, ContentType type) {
        Source<ByteString, CompletionStage<IOResult>> source = StreamConverters.fromInputStream(
            () -> new FileInputStream("/Users/me/file.xml"));

        Sink<ByteString, CompletionStage<Done>> sink = upload(key, type);
        source.toMat(sink, (m1,m2) -> m2)
            .run(materializer)
            .thenRun(() -> {
                System.out.println("done");
            });
    }

    public static void main(String[] args) {
        AlpakkaExample example = new AlpakkaExample();
        example.testUpload("keyWith%", ContentTypes.TEXT_XML_UTF8);
    }
}
```

Here is the exception caught by Alpakka S3:
```
akka.stream.alpakka.s3.impl.FailedUpload: Cannot find etag                            
        at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$completionSink$2(S3Stream.scala:232)                                                
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)                                                                      
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)                                                          
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)                                                                      
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)                                              
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)                                           
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)                                                            
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)                                                            
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)                                                      
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)                                                                     
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)                           
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)                                                                 
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)                                                     
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)                                                             
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

changing provider to memory or removing % from key resolves the problem.
Apparently there is a problem with key encoding and writing to file system. Note that when using AWS SDK to creater multipart upload, this problem doesn't occur and it only comes up when using Alpakka S3.

**Comment by vizog** [comment]
I added a PR to fix the problem: https://github.com/findify/s3mock/pull/78

The problem is that the key name which is url encoded, is sent back to the client (alpakka s3) in response of multipart upload, the client re-encodes it in the next command so the key which is double encoded is not found.
