### ISSUE TITLE
Thread safety issue

### ISSUE THREAD

**Issue by l15k4** [findify/s3mock#86]
Hey, I believe that s3mock is not thread safe. Let say you have 10 test classes that each extends this trait https://gist.github.com/l15k4/51c6fea1c364d4535c3143643b55f491 (Notice that the port is random), each in different sbt project (parallel execution)

Then the execution fails on : 
```
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at gwi.partitioner.S3Driver$S3Pimp.$anonfun$readObjectGZipStreamLines$1(S3Driver.scala:104)
```
However running those test classes one by one succeeds.

Therefore I suspect that there is some global static variable being mutated and that creating one s3mock instance per thread doesn't allow for thread safety.

**Comment by l15k4** [comment]
I have to give up, it's a totally strange issue. I'm using alpakka 0.16 with custom endpoint and `pathStyleAccess = true`
